title: Jose Delgado
email: TBD
description: >- 
  Jose Delgado | Software Dev | Reader | Occassional Gamer | Dog lover
  
baseurl: /docs/ 
url:  https://jgdelgado09.github.io 
twitter_username: 
github_username:  jgdelgado09

# Build settings
theme: minima
plugins:
  - jekyll-feed


